CREATE TABLE attendance_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    appointment_id UUID NOT NULL,
    patient_id UUID NOT NULL,
    collaborator_id UUID NOT NULL,
    checked_by_user_id UUID,
    status VARCHAR(50) NOT NULL CONSTRAINT ck_attendance_status CHECK (status IN ('present', 'absent', 'late', 'canceled')),
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    notes_required BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_att_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_att_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    CONSTRAINT fk_att_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE RESTRICT,
    CONSTRAINT fk_att_collaborator FOREIGN KEY (collaborator_id) REFERENCES collaborators(id) ON DELETE RESTRICT,
    CONSTRAINT fk_att_checker FOREIGN KEY (checked_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT uq_att_appointment UNIQUE (tenant_id, appointment_id)
);